#!/bin/sh

if [[ `cat /etc/*-release | head -1` =~ .*CentOS.* || `cat /etc/*-release | head -1` =~ .*CloudLinux.* ]]; then
        echo "******************************************"
        echo Found CentOS installation.
	sudo yum install epel-release -y
	sudo yum repolist -y
	sudo yum install dpkg-devel dpkg-dev -y
fi

dpkg --purge `dpkg --list|grep "linux-"|grep -v \`uname -r|sed 's/-generic//g'\`|cut -d" " -f3|grep "[0-9]-"|paste -sd " " -`

exit
# mamku ebal
