#!/bin/bash

# Debug
# set -x

swap=$(free -k | grep "Swap" |  awk '{print $3}')
mem=$(free -k | grep "Mem" |  awk '{print $4}')
swapp=$(cat /proc/sys/vm/swappiness)

if [ $mem -ge $swap ] ; then
        swapoff -a && swapon -a
        echo "Swap has been cleaned"
else
echo "No free memory to restart swap"
fi

echo "Swapiness: $swapp"
exit

