#!/bin/bash
# set -x

read -p 'Do you wanna see all processes? (default - 15) : ' choise 

echo

case "$choise" in 
[y/Y]) lines=1000 ;; 
*) lines=15 ;; 
esac 

ps aux | awk '{print $6/1024 " MB\t\t" $11}' | sort -n | tail -n$lines

exit
