#!/bin/bash
# set -x

read -p 'Do you wanna see all processes? (default - 15)' choise 

echo

case "$choise" in
1) lines=1 ;;
2) lines=2 ;;
3) lines=3 ;;
4) lines=4 ;;
5) lines=5 ;;
10) lines=10 ;;
*) lines=15 ;;
esac

grep VmSwap /proc/*/status 2>/dev/null | sort -nk2 | tail -n$lines |awk -F'/' '{cmd="cat /proc/" $3 "/cmdline"; cmd|getline var; close (cmd); printf $0 "\t"; print var}' |awk '{printf $2/1024 " MB" "\t";print $1 "\t\t" $4}'

exit
