#!/bin/sh

# size of swapfile in megabytes

read -p "Enter size of swap in MB : " swapsize

# does the swap file already exist?
grep -q "swapfile" /etc/fstab

# if not then create it
if [ $? -ne 0 ]; then
  echo 'Swapfile not found. Adding swapfile.'
  dd if=/dev/zero of=/swapfile bs=$swapsize count=1048576
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile swap swap defaults 0 0' >> /etc/fstab
else
  echo 'Swapfile found. No changes made.'
fi

# output results to terminal
df -h
echo ""
cat /proc/swaps
echo ""
cat /proc/meminfo | grep Swap

exit
